#!/usr/bin/env python3

import sys
from fxns import get_branch_name

# get commit message file name
commit_msg_filepath = sys.argv[1]


# Figure out which branch we're on

# print("commit-msg:",
#     f"\n\tFile: {commit_msg_filepath}",
#     f"\n\tBranch: {get_branch_name()}",
# )

# issue_number = get_branch_name().split('-')[0]

# try:
#     issue_number = int(issue_number)
# except ValueError:
#     print(f"commit-msg: Branch '{get_branch_name()}' does not start with an issue number")
#     sys.exit(1)
