#!/usr/bin/env python3

import sys, os, re
from subprocess import check_output

# get commit message file name
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode('utf-8')

print("commit-msg:",
    f"\n\tFile: {commit_msg_filepath}",
    f"\n\tBranch: {branch}",
)

# issue_number = branch.split('-')[0]

# try:
#     issue_number = int(issue_number)
# except ValueError:
#     print(f"commit-msg: Branch '{branch}' does not start with an issue number")
#     sys.exit(1)