#!/usr/bin/env python3

import sys
from subprocess import check_output

# get commit message file name
commit_msg_filepath = sys.argv[1]


def get_commit_ct():
    commit_ct_main = int(check_output(
        ['git', 'rev-list', '--count', 'HEAD']).strip().decode('utf-8'))
    commit_ct_head = int(check_output(
        ['git', 'rev-list', '--count', 'HEAD']).strip().decode('utf-8'))

    commit_ct_branch = commit_ct_main - commit_ct_head

    return {commit_ct_branch, commit_ct_main}

# Figure out which branch we're on
def get_branch_name():
    return check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode('utf-8')

# print("commit-msg:",
#     f"\n\tFile: {commit_msg_filepath}",
#     f"\n\tBranch: {branch}",
# )

# issue_number = branch.split('-')[0]

# try:
#     issue_number = int(issue_number)
# except ValueError:
#     print(f"commit-msg: Branch '{branch}' does not start with an issue number")
#     sys.exit(1)
