#!/usr/bin/env python3

import sys
from fxns import get_branch_name

# Collect the parameters
commit_msg_filepath = sys.argv[1]
commit_type = ""
commit_hash = ""
if len(sys.argv) > 2:
    commit_type = sys.argv[2]
if len(sys.argv) > 3:
    commit_hash = sys.argv[3]

# Figure out which branch we're on
branch_name = get_branch_name()

def update_commit_msg_file(commit_msg_filepath, issue_number):
    with open(commit_msg_filepath, 'r+') as f:
        existing_commit_msg = f.read()

        # check if issue number is included in the commit title
        if existing_commit_msg[0] != '(':
            msg = f"({issue_number}) {existing_commit_msg}"
            f.seek(0, 0)
            f.write(msg)
            f.close()

# try to get the issue number from the branch name
#   - if exists, use issue number from branch name
#   - if not, use default "000" issue number
issue_number_str = branch_name.split('-')[0]
try:
    issue_number = int(issue_number_str)
    update_commit_msg_file(commit_msg_filepath, issue_number)

except (IndexError, ValueError):
    issue_number = "000"
    update_commit_msg_file(commit_msg_filepath, issue_number)
